### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by barnikle00** [xcode75/XMPlus#3]
Hi
I just get this error with every protocol that i config?
unsupported protocol scheme
and it will not start

**Comment by xcode75** [comment]
> Hi I just get this error with every protocol that i config? unsupported protocol scheme and it will not start

you need to provide a log, without it i cannot help you.

**Comment by barnikle00** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
