### ISSUE TITLE
Backend config error

### ISSUE THREAD

**Issue by barnikle00** [xcode75/XMPlus#4]
Hi I just get this error with every protocol that i config? unsupported protocol scheme and it will not start

**Comment by paytakhtgithub** [comment]
Same here

**Comment by paytakhtgithub** [comment]
I get certificate signed by unknown authority.
I have used Let'sEncrypt but I'm getting this error back and forth
![2023-01-04 (1)](https://user-images.githubusercontent.com/121974702/210634334-081c3fd1-4c64-4951-89c3-17853c006010.png)
config.y
![2023-01-04 (2)](https://user-images.githubusercontent.com/121974702/210634674-6778e7b6-2f9b-492d-b507-7c1f5ff77498.png)
ml:

**Comment by xcode75** [comment]
> Hi I just get this error with every protocol that i config? unsupported protocol scheme and it will not start
> 
> ![IMG_20230104_141143_463](https://user-images.githubusercontent.com/54471348/210620968-22c2bdec-c171-4e70-bfbf-766eeb5ce4a1.jpg)

your issue is with scheme, must add http:// or https:// to you config.yml apihost

**Comment by xcode75** [comment]
> I get certificate signed by unknown authority. I have used Let'sEncrypt but I'm getting this error back and forth ![2023-01-04 (1)](https://user-images.githubusercontent.com/121974702/210634334-081c3fd1-4c64-4951-89c3-17853c006010.png) config.yml: ![2023-01-04 (2)](https://user-images.githubusercontent.com/121974702/210634674-6778e7b6-2f9b-492d-b507-7c1f5ff77498.png)

your issue is the site address cert

**Comment by xcode75** [comment]
both issues has nothing to do with backend

**Comment by xcode75** [comment]
> > Hi I just get this error with every protocol that i config? unsupported protocol scheme and it will not start
> > ![IMG_20230104_141143_463](https://user-images.githubusercontent.com/54471348/210620968-22c2bdec-c171-4e70-bfbf-766eeb5ce4a1.jpg)
> 
> your issue is with scheme, must add http:// or https:// to you config.yml apihost

update your backend to v2.0.3 as well,  xmplus update

**Comment by barnikle00** [comment]
Thank you so much

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by paytakhtgithub** [comment]
I got "panic: Unsupported Node Type:"
![image](https://user-images.githubusercontent.com/121974702/210832682-8cc3a2fd-96d4-4c92-8eff-fae667955051.png)
