### ISSUE TITLE
XMPlus server connection logs for debug

### ISSUE THREAD

**Issue by dadashali61** [xcode75/XMPlus#7]
How can we check logs to debug connections? in XMPlus log option on the menu, there is nothing about that. I made several connections even if it is green (connected) but I can't get any ping via "https://tcp.ping.pe/" and all connections will be refused if I setup another Xray server on it so everything is ok!

![Untitled-2](https://user-images.githubusercontent.com/88386604/211218318-2a4d5aa8-e63e-410c-8b21-95c7d99551e4.jpg)

-- Logs begin at Sat 2023-01-07 07:27:30 UTC. --
Jan 07 09:07:01 centos-2gb-nbg1-3 systemd[1]: Stopping XMPlus Service...
Jan 07 09:07:01 centos-2gb-nbg1-3 systemd[1]: Stopped XMPlus Service.
Jan 07 09:07:01 centos-2gb-nbg1-3 systemd[1]: Started XMPlus Service.
Jan 07 09:07:01 centos-2gb-nbg1-3 XMPlus[10153]: XMPlus v2.0.3 (A custom version of XrayR)
Jan 07 09:07:01 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:01 Starting XMPlus
Jan 07 09:07:01 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:01 [Warning] core: Xray 1.6.6 started
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created Remote DOH client for https://dns.google/dns-query
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created Remote DOH client for https://1.1.1.1/dns-query
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created Local DOH client for https://cloudflare-dns.com/dns-query
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [http://sub.site..com] Vless(NodeID=1) 1 New Users Added
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [http://sub.site..com] Vless(NodeID=1) Task Scheduler for node monitor started
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [http://sub.site..com] Vless(NodeID=1) Task Scheduler for user monitor started
Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:6661

**Comment by xcode75** [comment]
> How can we check logs to debug connections? in XMPlus log option on the menu, there is nothing about that. I made several connections even if it is green (connected) but I can't get any ping via "https://tcp.ping.pe/" and all connections will be refused if I setup another Xray server on it so everything is ok!
> 
> ![Untitled-2](https://user-images.githubusercontent.com/88386604/211218318-2a4d5aa8-e63e-410c-8b21-95c7d99551e4.jpg)
> 
> -- Logs begin at Sat 2023-01-07 07:27:30 UTC. -- Jan 07 09:07:01 centos-2gb-nbg1-3 systemd[1]: Stopping XMPlus Service... Jan 07 09:07:01 centos-2gb-nbg1-3 systemd[1]: Stopped XMPlus Service. Jan 07 09:07:01 centos-2gb-nbg1-3 systemd[1]: Started XMPlus Service. Jan 07 09:07:01 centos-2gb-nbg1-3 XMPlus[10153]: XMPlus v2.0.3 (A custom version of XrayR) Jan 07 09:07:01 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:01 Starting XMPlus Jan 07 09:07:01 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:01 [Warning] core: Xray 1.6.6 started Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53 Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53 Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created Remote DOH client for https://dns.google/dns-query Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created Remote DOH client for https://1.1.1.1/dns-query Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] app/dns: DNS: created Local DOH client for https://cloudflare-dns.com/dns-query Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [http://sub.site..com] Vless(NodeID=1) 1 New Users Added Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [http://sub.site..com] Vless(NodeID=1) Task Scheduler for node monitor started Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [http://sub.site..com] Vless(NodeID=1) Task Scheduler for user monitor started Jan 07 09:07:02 centos-2gb-nbg1-3 XMPlus[10153]: 2023/01/07 09:07:02 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:6661

there is nothing wrong with the backend, you are seeing the log.
The issue will be you have not allow your server port through your firewall or security group
