### ISSUE TITLE
XMPlus.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by ehsan0github** [xcode75/XMPlus#8]
This error comes and when I go to that address in github, I get a 404 error
Please help, where is the error?
It works with Nginx
![Screenshot 2023-01-24 042116](https://user-images.githubusercontent.com/123427867/214190080-f1248b51-7015-48e2-891e-addc02544464.jpg)
![Screenshot 2023-01-24 042040](https://user-images.githubusercontent.com/123427867/214190092-2716cfc0-db95-44ef-9b9b-f50de545c944.jpg)
![Screenshot 2023-01-24 042008](https://user-images.githubusercontent.com/123427867/214190098-e6d11181-ece1-49fc-a2f3-1ce1a91b8eae.jpg)
![Screenshot 2023-01-24 041830](https://user-images.githubusercontent.com/123427867/214190109-3537953d-891c-4de8-9e9c-58730706c364.jpg)

Jan 24 00:22:53 Ehsan XMPlus[234128]: 2023/01/24 00:22:53 Starting XMPlus
Jan 24 00:22:56 Ehsan XMPlus[234128]: 2023/01/24 00:22:56 Unsupported Node Type:
Jan 24 00:22:56 Ehsan XMPlus[234128]: panic: Unsupported Node Type:
Jan 24 00:22:56 Ehsan XMPlus[234128]: goroutine 1 [running]:
Jan 24 00:22:56 Ehsan XMPlus[234128]: log.Panic({0xc000cb1d28?, 0xc000d02000?, 0xc0006a7d80?})
Jan 24 00:22:56 Ehsan XMPlus[234128]:         log/log.go:388 +0x65
Jan 24 00:22:56 Ehsan XMPlus[234128]: github.com/xcode75/XMPlus/service/controller.(*Controller).Start(0xc000590b00)
Jan 24 00:22:56 Ehsan XMPlus[234128]:         github.com/xcode75/XMPlus/service/controller/controller.go:114 +0x618
Jan 24 00:22:56 Ehsan XMPlus[234128]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0001231c0)
Jan 24 00:22:56 Ehsan XMPlus[234128]:         github.com/xcode75/XMPlus/panel/panel.go:184 +0x39a
Jan 24 00:22:56 Ehsan XMPlus[234128]: main.main()
Jan 24 00:22:56 Ehsan XMPlus[234128]:         github.com/xcode75/XMPlus/main/main.go:95 +0x2bf
Jan 24 00:22:56 Ehsan systemd[1]: XMPlus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 24 00:22:56 Ehsan systemd[1]: XMPlus.service: Failed with result 'exit-code'.

**Comment by xcode75** [comment]
okay will take a look into that

**Comment by xcode75** [comment]
Check your backend api address and node id
